### ISSUE TITLE
bxcan/defmt  version conflict

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32f0xx-hal#133]
In code that uses multiple device crates I have started having `cargo update` problems because of the change in the dependency  `bxcan = "0.4"` (see https://github.com/stm32-rs/bxcan/issues/22#issue-848677821 and https://github.com/stm32-rs/stm32f7xx-hal/issues/114#issue-848734979). Can the dependency be more flexible, say `bxcan = ">=0.4"` ?

**Comment by newAM** [comment]
Going through old issues - looks like this one can be closed now with defmt 0.3 / bxcan 0.6 in #146; feel free to reopen if that did not resolve this.

**Comment by pdgilbert** [comment]
Seems to be fixed. Thanks.
