### ISSUE TITLE
SPI on 0.17.1 is broken

### ISSUE THREAD

**Issue by romixlab** [stm32-rs/stm32f0xx-hal#139]
Absolutely the same code is working fine on 0.16 and doesn't on 0.17. I believe this is due to some performance updates merged lately. There is simply nothing on SCK or MOSI pins. Initialisation code is stanard:
```rust
const MODE: Mode = Mode {
        polarity: Polarity::IdleLow,
        phase: Phase::CaptureOnFirstTransition,
};
let spi = Spi::spi1(p.SPI1, (mcp_sck, mcp_miso, mcp_mosi), MODE, spi_freq, &mut rcc);
```
Usage is also standard, `write` and `transfer` methods are used.

![image](https://user-images.githubusercontent.com/6066470/125190058-8fe48c80-e23b-11eb-824d-fc82cecd1de7.png)
![image](https://user-images.githubusercontent.com/6066470/125190073-a12d9900-e23b-11eb-8e80-42f76165deba.png)

**Comment by therealprof** [comment]
Sorry for the late reply. Have you tried whether master addresses your problem?

**Comment by romixlab** [comment]
Seems to be working fine, not sure which commit fixed it though. If you can point it out, I can double check both.

**Comment by therealprof** [comment]
No worries, just want to make sure this has been adressed already, thanks! Will close this issue then.
