### ISSUE TITLE
Flash Driver

### ISSUE THREAD

**Issue by imrank03** [stm32-rs/stm32f0xx-hal#149]
Hi I'm looking for a flash driver for stm32f091, can you help me with that?

**Comment by newAM** [comment]
There is no flash driver in this codebase yet.  If you want to create one there is usually a section on flash memory erase & program in the reference manual.

**Comment by imrank03** [comment]
> There is no flash driver in this codebase yet. If you want to create one there is usually a section on flash memory erase & program in the reference manual.

@newAM Okay thank you.
