### ISSUE TITLE
Side effects from using *const addresses

### ISSUE THREAD

**Issue by therealprof** [stm32-rs/stm32f0xx-hal#15]
I just noticed that using `*const` means we can't share peripherals between interrupt/exception handlers and main anymore:
```
error[E0277]: `*const stm32f0::stm32f0x2::USART2` cannot be sent between threads safely
  --> examples/i2c_hal_ssd1306alphabeter.rs:23:1
   |
23 | / static PANIC_SERIAL: Mutex<RefCell<Option<hal::serial::Tx<USART2>>>> =
24 | |     Mutex::new(RefCell::new(None));
   | |___________________________________^ `*const stm32f0::stm32f0x2::USART2` cannot be sent between threads safely
```

cc @HarkonenBade @david-sawatzke

**Comment by david-sawatzke** [comment]
`Pin` (of course) also doesn't implement Sync

**Comment by david-sawatzke** [comment]
We should implement Sync for Rx, Tx and Pin. They don't have rmw cycles, so they are safe from race conditions. I don't see any reason to have Send for Rx & Tx, but it's useful for Pin.

**Comment by therealprof** [comment]
This has been addressed.
