### ISSUE TITLE
How to handle race conditions with shared peripherals?

### ISSUE THREAD

**Issue by david-sawatzke** [stm32-rs/stm32f0xx-hal#24]
Addresses https://github.com/stm32-rs/stm32f0xx-hal/issues/15#issuecomment-449529219. We have a couple race conditions:
1. The $PXi types are send, but setting the alternate mode does a RMW to a shared register
    
    I'd add a GPIO specific `GpioShared` struct which is in parts and needs to be passed as a `&mut` to the mode settings (af, pp, hs, od) and pull-up/down config. 

2. The register modification to enable peripherals also suffer from race conditions.

    Something like a token returned in the Rcc struct that has to be passed to the new methods, similar to the Gpio thing.

That makes the api a bit more annoying but safe. If can't think of better ways, but there are probably some

**Comment by therealprof** [comment]
Yeah but to be honest that's way down my priority list. It's almost impossible to run into a race situation without actively trying and even then it's very hard. There're far easier ways to make a MCU glitch...

The easy way out would be taking a `CriticalSection` for initialisation.

**Comment by david-sawatzke** [comment]
Fixed by #41
