### ISSUE TITLE
Need to cfg-gate HSI48 use to only work on supported hardware

### ISSUE THREAD

**Issue by therealprof** [stm32-rs/stm32f0xx-hal#45]
We should prevent the use of HSI48 on devices which don't support it.

cf.

https://github.com/stm32-rs/stm32f0xx-hal/blob/master/src/rcc.rs#L34
https://github.com/stm32-rs/stm32f0xx-hal/blob/master/src/rcc.rs#L90
https://github.com/stm32-rs/stm32f0xx-hal/blob/master/src/rcc.rs#L169

et al

CC @bentwire

**Comment by HarkonenBade** [comment]
@therealprof Has this now been solved?

**Comment by therealprof** [comment]
Seems you've fixed it.
