### ISSUE TITLE
Support remaining stm32f0xx devices

### ISSUE THREAD

**Issue by jessebraham** [stm32-rs/stm32f0xx-hal#49]
Each of the `stm32f0x0`, `stm32f0x1`, and `stm32f0x2` lines have had support added at this time. The only remaining devices belong to the `stm32f0x8` line, and are as follows:

- STM32F038
- STM32F048
- STM32F058
- STM32F078
- STM32F098

If nobody else feels like hopping on these I will likely start picking away at them shortly, but just wanted to document the progress made thus far.

**Comment by therealprof** [comment]
Go for it! 👍
