### ISSUE TITLE
Flags are never cleared when there's a UART error

### ISSUE THREAD

**Issue by thejpster** [stm32-rs/stm32f0xx-hal#61]
If there's a UART error (for example, it receives a byte when there's already a byte in the Receive Data Register), a sticky flag gets set. This flag causes `read()` to return an error, but the flag doesn't get cleared. So every subsequent `read()` also returns an error.

I propose you clear the flag by writing to the appropriate bit in `icf` just before the error is returned.

**Comment by therealprof** [comment]
@thejpster Any chance you could test the PR? Having troubles creating errors here... ;)

**Comment by thejpster** [comment]
The easiest way to generate an error is to write two characters to the UART, without reading the first one first. This will trigger a UART data overflow error.
